"use client";

import { useMemo, useState } from "react";
import { Check, Download, FileSpreadsheet, Pencil, Plus, Printer, ReceiptText, ShieldCheck, Trash2, WalletCards, X } from "lucide-react";
import { AIWritingButton } from "@/components/ai-writing-button";
import { HRMSAIInsight } from "@/components/hrms-ai-insight";
import { HRPayroll } from "@/components/hrms-extended-sections";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { DateInput } from "@/components/date-input";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { cn } from "@/lib/utils";

type View = "runs" | "yearly" | "vouchers";
const money = (value: unknown) => `RM ${Number(value || 0).toLocaleString("en-MY", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const today = () => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Kuala_Lumpur", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());

export function HRMSPayrollWorkbench({ records, vouchers, employees, employeeName, canManage, onCreatePayroll, onEditPayroll, onPayrollAction, onCreateVoucher, onUpdateVoucher, onDeleteVoucher, onVoucherAction }: any) {
  const [view, setView] = useState<View>("runs"); const tabs: { id: View; label: string }[] = canManage ? [{ id: "runs", label: "Payroll runs" }, { id: "yearly", label: "Yearly forms" }, { id: "vouchers", label: "Payment vouchers" }] : [{ id: "runs", label: "My payslips" }];
  return <div className="space-y-4">{canManage && <div className="overflow-x-auto rounded-2xl border bg-white p-1.5 shadow-sm"><div className="flex min-w-max gap-1">{tabs.map((item) => <button key={item.id} onClick={() => setView(item.id)} className={cn("rounded-xl px-4 py-2.5 text-xs font-semibold sm:text-sm", view === item.id ? "bg-[#202c25] text-white" : "text-[#687269]")}>{item.label}</button>)}</div></div>}{view === "runs" && <><HRPayroll records={records} employeeName={employeeName} canManage={canManage} onCreate={onCreatePayroll} onEdit={onEditPayroll} onAction={onPayrollAction} />{canManage && <PayrollAI records={records} />}</>}{view === "yearly" && <Yearly records={records} employees={employees} />}{view === "vouchers" && <Vouchers vouchers={vouchers} employees={employees} onCreate={onCreateVoucher} onUpdate={onUpdateVoucher} onDelete={onDeleteVoucher} onAction={onVoucherAction} />}</div>;
}

function PayrollAI({ records }: any) { const period = String(([...new Set<string>(records.map((item: any) => String(item.period || "")).filter(Boolean))].sort().reverse()[0]) || "Current period"); const metrics = records.filter((item: any) => item.period === period).map((item: any, index: number) => ({ label: `Employee ${index + 1}`, status: item.status, grossPay: Number(item.grossPay || 0), netPay: Number(item.netPay || 0), totalDeductions: Number(item.totalDeductions || 0), epfEmployee: Number(item.epfEmployee || 0), socsoEmployee: Number(item.socsoEmployee || 0), eisEmployee: Number(item.eisEmployee || 0), pcb: Number(item.pcb || 0), hasVerificationNote: Boolean(item.verificationNote) })); return <HRMSAIInsight task="payroll_review" period={period} metrics={metrics} context="Flag completeness or unusual differences only. Do not calculate or confirm statutory compliance." label="Review payroll" />; }

function Yearly({ records, employees }: any) {
  const years = [...new Set(records.map((item: any) => String(item.period || "").slice(0, 4)).filter(Boolean))].sort().reverse() as string[]; const [year, setYear] = useState(years[0] || String(new Date().getFullYear())); const [form, setForm] = useState<"E" | "EA" | "CP">("E"); const closed = records.filter((item: any) => String(item.period).startsWith(year) && ["Closed", "Paid"].includes(item.status));
  const sum = (items: any[]) => items.reduce((total, item) => ({ gross: total.gross + Number(item.grossPay || 0), net: total.net + Number(item.netPay || 0), epf: total.epf + Number(item.epfEmployee || 0) + Number(item.epfEmployer || 0), socso: total.socso + Number(item.socsoEmployee || 0) + Number(item.socsoEmployer || 0), eis: total.eis + Number(item.eisEmployee || 0) + Number(item.eisEmployer || 0), pcb: total.pcb + Number(item.pcb || 0) }), { gross: 0, net: 0, epf: 0, socso: 0, eis: 0, pcb: 0 });
  const annual = useMemo(() => employees.map((employee: any) => { const items = closed.filter((item: any) => item.employeeId === employee.id); return { name: employee.name, months: items.length, ...sum(items) }; }).filter((item: any) => item.months), [closed, employees]); const monthly = Array.from({ length: 12 }, (_, index) => { const month = `${year}-${String(index + 1).padStart(2, "0")}`; const items = closed.filter((item: any) => item.period === month); return { name: month, months: items.length, ...sum(items) }; }); const total = sum(closed);
  const headers = form === "EA" ? ["Employee", "Months", "Gross", "EPF", "SOCSO", "EIS", "PCB", "Net"] : form === "CP" ? ["Month", "Records", "Gross", "PCB", "Net"] : ["Year", "Employees", "Records", "Gross", "EPF", "SOCSO", "EIS", "PCB", "Net"];
  const rows: any[][] = form === "EA" ? annual.map((item: any) => [item.name, item.months, item.gross, item.epf, item.socso, item.eis, item.pcb, item.net]) : form === "CP" ? monthly.map((item: any) => [item.name, item.months, item.gross, item.pcb, item.net]) : [[year, annual.length, closed.length, total.gross, total.epf, total.socso, total.eis, total.pcb, total.net]];
  function csv() { const content = [headers, ...rows].map((row: any[]) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(",")).join("\n"); const url = URL.createObjectURL(new Blob([content], { type: "text/csv" })); const link = document.createElement("a"); link.href = url; link.download = `payroll-working-paper-${form}-${year}.csv`; link.click(); URL.revokeObjectURL(url); }
  return <div className="space-y-4"><Card className="border-amber-200 bg-amber-50"><CardContent className="flex gap-3 p-4"><ShieldCheck className="h-4 w-4 shrink-0 text-amber-700" /><p className="text-xs leading-5 text-amber-900">Internal payroll working papers only—not official LHDN forms or filing. Verify figures and use the current official portal/form.</p></CardContent></Card><Card className="border-black/8 bg-white/90"><CardContent className="p-5"><div className="flex flex-wrap items-end gap-3"><label className="text-xs font-medium">Year<Select className="mt-2" value={year} onChange={(e) => setYear(e.target.value)}>{[...new Set([year, ...years])].map((item) => <option key={item}>{item}</option>)}</Select></label><div className="flex-1" /><Button variant="outline" onClick={csv}><Download className="h-4 w-4" />CSV</Button><Button variant="outline" onClick={() => window.print()}><Printer className="h-4 w-4" />Print</Button></div><div className="mt-5 grid gap-3 sm:grid-cols-3">{(["E", "EA", "CP"] as const).map((item) => <button key={item} onClick={() => setForm(item)} className={cn("rounded-2xl border p-5 text-left", form === item ? "bg-[#202c25] text-white" : "bg-[#fbfaf7]")}><FileSpreadsheet className="h-5 w-5" /><b className="mt-4 block">Form {item}</b><span className="mt-1 block text-[10px] opacity-60">{item === "E" ? "Employer annual summary" : item === "EA" ? "Employee annual summary" : "Monthly payroll/PCB working paper"}</span></button>)}</div></CardContent></Card><Card className="overflow-hidden border-black/8 bg-white/90"><CardContent className="p-0"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead className="bg-[#f4f1e9]"><tr>{headers.map((item) => <th key={item} className="p-4">{item}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index} className="border-t">{row.map((cell, cellIndex) => <td key={cellIndex} className="p-4">{typeof cell === "number" && cellIndex > 1 ? money(cell) : String(cell)}</td>)}</tr>)}</tbody></table></div></CardContent></Card></div>;
}

function Vouchers({ vouchers, employees, onCreate, onUpdate, onDelete, onAction }: any) { const [editing, setEditing] = useState<any>(null); const blank = () => ({ employeeId: "", payee: "", amount: 0, details: "", paymentDate: today(), linkedType: "General", linkedId: "" }); async function save() { if (editing.id) await onUpdate(editing); else await onCreate(editing); setEditing(null); } return <div className="space-y-4"><Card className="border-black/8 bg-white/90"><CardContent className="flex items-center gap-4 p-5"><div className="flex-1"><h2 className="font-semibold">Payment vouchers</h2><p className="mt-1 text-xs text-muted-foreground">Supporting evidence only; no duplicate accounting entry is created.</p></div><Button onClick={() => setEditing(blank())}><Plus className="h-4 w-4" />Create voucher</Button></CardContent></Card>{vouchers.map((item: any) => <Card key={item.id} className="border-black/8 bg-white/90"><CardContent className="flex flex-col gap-4 p-5 lg:flex-row lg:items-center"><WalletCards className="h-5 w-5 text-[#ba5c42]" /><div className="flex-1"><div className="flex items-center gap-2"><b>{item.payee}</b><Badge value={item.status} /></div><p className="mt-1 text-xs text-muted-foreground">{item.reference} · {item.paymentDate} · {item.linkedType}</p><p className="mt-2 text-xs">{item.details}</p></div><b>{money(item.amount)}</b><div className="flex gap-2">{item.status === "Draft" && <><Button size="sm" variant="outline" onClick={() => setEditing({ ...item })}><Pencil className="h-3.5 w-3.5" />Edit</Button><Button size="sm" onClick={() => onAction(item.id, "approve")}><Check className="h-3.5 w-3.5" />Approve</Button><Button size="icon" variant="outline" onClick={() => onDelete(item.id)}><Trash2 className="h-4 w-4 text-red-500" /></Button></>}{item.status === "Approved" && <><Button size="sm" onClick={() => onAction(item.id, "mark_paid")}>Mark paid</Button><Button size="sm" variant="outline" onClick={() => onAction(item.id, "cancel")}><X className="h-3.5 w-3.5" />Cancel</Button></>}<Button size="sm" variant="outline" onClick={() => window.print()}><Printer className="h-3.5 w-3.5" />Print</Button></div></CardContent></Card>)}{!vouchers.length && <div className="rounded-2xl border border-dashed p-10 text-center"><ReceiptText className="mx-auto h-7 w-7 text-muted-foreground" /><b className="mt-3 block">No payment vouchers</b></div>}{editing && <VoucherDialog draft={editing} setDraft={setEditing} employees={employees} onClose={() => setEditing(null)} onSave={save} />}</div>; }
function VoucherDialog({ draft, setDraft, employees, onClose, onSave }: any) {
  const update = (key: string, value: any) => setDraft({ ...draft, [key]: value });
  return <div className="fixed inset-0 z-[80] flex items-end justify-center bg-black/35 sm:items-center sm:p-4"><Card className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-b-none bg-[#f7f4ed] sm:rounded-2xl"><CardContent className="p-5"><div className="flex items-start justify-between gap-3"><h2 className="text-xl font-semibold">{draft.id ? `Edit ${draft.reference}` : "Create payment voucher"}</h2><Button variant="ghost" size="icon" onClick={onClose} aria-label="Close payment voucher editor"><X className="h-4 w-4" /></Button></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Payee"><Input value={draft.payee} onChange={(e) => update("payee", e.target.value)} /></Field><Field label="Amount (RM)"><Input type="number" min="0" step="0.01" value={draft.amount} onChange={(e) => update("amount", Number(e.target.value))} /></Field><Field label="Payment date"><DateInput value={draft.paymentDate} onChange={(e) => update("paymentDate", e.target.value)} /></Field><Field label="Link type"><Select value={draft.linkedType} onChange={(e) => update("linkedType", e.target.value)}><option>General</option><option>Claim</option><option>Payroll</option></Select></Field><Field label="Linked team member"><Select value={draft.employeeId} onChange={(e) => update("employeeId", e.target.value)}><option value="">Not linked</option>{employees.map((item: any) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></Field><Field label="Linked record ID"><Input value={draft.linkedId} onChange={(e) => update("linkedId", e.target.value)} /></Field><div className="sm:col-span-2"><div className="mb-2 flex items-center justify-between"><span className="text-xs font-medium">Payment details</span><AIWritingButton value={draft.details} field="Payment voucher details" context="Internal HR payment voucher. Keep names, dates, amounts and purpose exact. Do not invent approval or accounting status." onApply={(value) => update("details", value)} /></div><Textarea className="min-h-28" value={draft.details} onChange={(e) => update("details", e.target.value)} /></div></div><div className="mt-6 flex justify-end gap-2"><Button variant="outline" onClick={onClose}>Cancel</Button><Button onClick={onSave}>Save voucher</Button></div></CardContent></Card></div>;
}
function Field({ label, children }: any) { return <label className="text-xs font-medium"><span className="mb-2 block">{label}</span>{children}</label>; }
function Badge({ value }: any) { return <span className={cn("rounded-full px-2 py-1 text-[10px]", value === "Paid" ? "bg-emerald-50 text-emerald-700" : value === "Approved" ? "bg-blue-50 text-blue-700" : "bg-amber-50 text-amber-700")}>{value}</span>; }
